import { Product, User, Table, Order, Attendance, Expense, Branch } from './types';

// ==================== Branch ====================

export const mockBranches: Branch[] = [
  {
    id: 'branch-1',
    name: 'Main Branch',
    location: '123 Main Street, Downtown',
    managerId: 'user-admin-1',
    isActive: true,
  },
];

// ==================== Users ====================

export const mockUsers: User[] = [
  {
    id: 'user-admin-1',
    name: 'Admin User',
    employmentNumber: 'EMP001',
    role: 'admin',
    pin: '1234',
    email: 'admin@storehub.com',
    status: 'active',
    branchId: 'branch-1',
    createdAt: new Date('2025-01-01'),
  },
  {
    id: 'user-cashier-1',
    name: 'Sarah Johnson',
    employmentNumber: 'EMP002',
    role: 'cashier',
    pin: '2345',
    email: 'sarah.j@storehub.com',
    status: 'active',
    branchId: 'branch-1',
    createdAt: new Date('2025-01-15'),
  },
  {
    id: 'user-waiter-1',
    name: 'Mike Chen',
    employmentNumber: 'EMP003',
    role: 'waiter',
    pin: '3456',
    email: 'mike.c@storehub.com',
    status: 'active',
    branchId: 'branch-1',
    createdAt: new Date('2025-02-01'),
  },
  {
    id: 'user-waiter-2',
    name: 'Emily Rodriguez',
    employmentNumber: 'EMP004',
    role: 'waiter',
    pin: '4567',
    email: 'emily.r@storehub.com',
    status: 'active',
    branchId: 'branch-1',
    createdAt: new Date('2025-02-10'),
  },
  {
    id: 'user-kitchen-1',
    name: 'James Kim',
    employmentNumber: 'EMP005',
    role: 'kitchen',
    pin: '5678',
    email: 'james.k@storehub.com',
    status: 'active',
    branchId: 'branch-1',
    createdAt: new Date('2025-01-20'),
  },
  {
    id: 'user-hr-1',
    name: 'Lisa Anderson',
    employmentNumber: 'EMP006',
    role: 'hr',
    pin: '6789',
    email: 'lisa.a@storehub.com',
    status: 'active',
    branchId: 'branch-1',
    createdAt: new Date('2025-01-10'),
  },
];

// ==================== Tables ====================

export const mockTables: Table[] = [
  {
    id: 'table-1',
    number: 1,
    capacity: 4,
    status: 'occupied',
    branchId: 'branch-1',
    currentOrderId: 'order-1',
    assignedCashierId: 'user-cashier-1',
  },
  {
    id: 'table-2',
    number: 2,
    capacity: 2,
    status: 'occupied',
    branchId: 'branch-1',
    currentOrderId: 'order-2',
    assignedCashierId: 'user-cashier-1',
  },
  {
    id: 'table-3',
    number: 3,
    capacity: 6,
    status: 'available',
    branchId: 'branch-1',
  },
  {
    id: 'table-4',
    number: 4,
    capacity: 4,
    status: 'available',
    branchId: 'branch-1',
  },
  {
    id: 'table-5',
    number: 5,
    capacity: 2,
    status: 'occupied',
    branchId: 'branch-1',
    currentOrderId: 'order-3',
    assignedCashierId: 'user-cashier-1',
  },
];

// ==================== Products ====================

export const mockProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'Classic Burger',
    category: 'Burgers',
    price: 8.99,
    stock: 45,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400&h=400&fit=crop',
    sku: 'BRG-001',
    taxRate: 0.10,
    reorderPoint: 20,
    branchId: 'branch-1',
    kitchenStatus: 'available',
    isActive: true,
  },
  {
    id: 'prod-2',
    name: 'Cheeseburger',
    category: 'Burgers',
    price: 9.99,
    stock: 38,
    image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=400&h=400&fit=crop',
    sku: 'BRG-002',
    taxRate: 0.10,
    reorderPoint: 20,
    branchId: 'branch-1',
    kitchenStatus: 'available',
    isActive: true,
  },
  {
    id: 'prod-3',
    name: 'French Fries',
    category: 'Sides',
    price: 3.99,
    stock: 67,
    image: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=400&h=400&fit=crop',
    sku: 'SID-001',
    taxRate: 0.10,
    reorderPoint: 30,
    branchId: 'branch-1',
    kitchenStatus: 'available',
    isActive: true,
  },
  {
    id: 'prod-4',
    name: 'Onion Rings',
    category: 'Sides',
    price: 4.49,
    stock: 52,
    image: 'https://images.unsplash.com/photo-1639024471283-03518883512d?w=400&h=400&fit=crop',
    sku: 'SID-002',
    taxRate: 0.10,
    reorderPoint: 25,
    branchId: 'branch-1',
    kitchenStatus: 'available',
    isActive: true,
  },
  {
    id: 'prod-5',
    name: 'Coca Cola',
    category: 'Beverages',
    price: 2.49,
    stock: 120,
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400&h=400&fit=crop',
    sku: 'BEV-001',
    taxRate: 0.08,
    reorderPoint: 50,
    branchId: 'branch-1',
    kitchenStatus: 'available',
    isActive: true,
  },
  {
    id: 'prod-6',
    name: 'Iced Coffee',
    category: 'Beverages',
    price: 3.99,
    stock: 18,
    image: 'https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=400&h=400&fit=crop',
    sku: 'BEV-002',
    taxRate: 0.08,
    reorderPoint: 20,
    branchId: 'branch-1',
    kitchenStatus: 'available',
    isActive: true,
  },
  {
    id: 'prod-7',
    name: 'Caesar Salad',
    category: 'Salads',
    price: 7.99,
    stock: 29,
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400&h=400&fit=crop',
    sku: 'SAL-001',
    taxRate: 0.10,
    reorderPoint: 15,
    branchId: 'branch-1',
    kitchenStatus: 'available',
    isActive: true,
  },
  {
    id: 'prod-8',
    name: 'Chicken Wings',
    category: 'Appetizers',
    price: 10.99,
    stock: 41,
    image: 'https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=400&h=400&fit=crop',
    sku: 'APP-001',
    taxRate: 0.10,
    reorderPoint: 20,
    branchId: 'branch-1',
    kitchenStatus: 'finished',
    isActive: true,
  },
];

// ==================== Orders ====================

export const mockOrders: Order[] = [
  {
    id: 'order-1',
    tableId: 'table-1',
    tableNumber: 1,
    items: [
      {
        id: 'item-1',
        productId: 'prod-1',
        productName: 'Classic Burger',
        quantity: 2,
        price: 8.99,
        subtotal: 17.98,
        addedBy: 'user-waiter-1',
        addedByName: 'Mike Chen',
        addedAt: new Date('2026-04-12T10:30:00'),
        status: 'ready',
      },
      {
        id: 'item-2',
        productId: 'prod-3',
        productName: 'French Fries',
        quantity: 2,
        price: 3.99,
        subtotal: 7.98,
        addedBy: 'user-waiter-1',
        addedByName: 'Mike Chen',
        addedAt: new Date('2026-04-12T10:30:00'),
        status: 'ready',
      },
      {
        id: 'item-3',
        productId: 'prod-5',
        productName: 'Coca Cola',
        quantity: 2,
        price: 2.49,
        subtotal: 4.98,
        addedBy: 'user-waiter-2',
        addedByName: 'Emily Rodriguez',
        addedAt: new Date('2026-04-12T10:35:00'),
        status: 'served',
      },
    ],
    subtotal: 30.94,
    tax: 3.05,
    discount: 0,
    total: 33.99,
    status: 'open',
    createdAt: new Date('2026-04-12T10:30:00'),
    waiters: ['user-waiter-1', 'user-waiter-2'],
  },
  {
    id: 'order-2',
    tableId: 'table-2',
    tableNumber: 2,
    items: [
      {
        id: 'item-4',
        productId: 'prod-2',
        productName: 'Cheeseburger',
        quantity: 1,
        price: 9.99,
        subtotal: 9.99,
        addedBy: 'user-waiter-2',
        addedByName: 'Emily Rodriguez',
        addedAt: new Date('2026-04-12T11:00:00'),
        status: 'preparing',
      },
      {
        id: 'item-5',
        productId: 'prod-4',
        productName: 'Onion Rings',
        quantity: 1,
        price: 4.49,
        subtotal: 4.49,
        addedBy: 'user-waiter-2',
        addedByName: 'Emily Rodriguez',
        addedAt: new Date('2026-04-12T11:00:00'),
        status: 'preparing',
      },
    ],
    subtotal: 14.48,
    tax: 1.45,
    discount: 0,
    total: 15.93,
    status: 'open',
    createdAt: new Date('2026-04-12T11:00:00'),
    waiters: ['user-waiter-2'],
  },
  {
    id: 'order-3',
    tableId: 'table-5',
    tableNumber: 5,
    items: [
      {
        id: 'item-6',
        productId: 'prod-7',
        productName: 'Caesar Salad',
        quantity: 1,
        price: 7.99,
        subtotal: 7.99,
        addedBy: 'user-waiter-1',
        addedByName: 'Mike Chen',
        addedAt: new Date('2026-04-12T11:30:00'),
        status: 'pending',
      },
    ],
    subtotal: 7.99,
    tax: 0.80,
    discount: 0,
    total: 8.79,
    status: 'open',
    createdAt: new Date('2026-04-12T11:30:00'),
    waiters: ['user-waiter-1'],
  },
];

// ==================== Attendance ====================

const today = new Date('2026-04-12');
const scheduledTime = new Date(today);
scheduledTime.setHours(9, 0, 0, 0);

export const mockAttendance: Attendance[] = [
  {
    id: 'att-1',
    employmentNumber: 'EMP002',
    staffId: 'user-cashier-1',
    staffName: 'Sarah Johnson',
    checkInTime: new Date('2026-04-12T09:00:00'),
    scheduledTime: scheduledTime,
    lateMinutes: 0,
    branchId: 'branch-1',
    date: '2026-04-12',
  },
  {
    id: 'att-2',
    employmentNumber: 'EMP003',
    staffId: 'user-waiter-1',
    staffName: 'Mike Chen',
    checkInTime: new Date('2026-04-12T09:05:00'),
    scheduledTime: scheduledTime,
    lateMinutes: 5,
    branchId: 'branch-1',
    date: '2026-04-12',
  },
  {
    id: 'att-3',
    employmentNumber: 'EMP004',
    staffId: 'user-waiter-2',
    staffName: 'Emily Rodriguez',
    checkInTime: new Date('2026-04-12T08:58:00'),
    scheduledTime: scheduledTime,
    lateMinutes: 0,
    branchId: 'branch-1',
    date: '2026-04-12',
  },
];

// ==================== Expenses ====================

export const mockExpenses: Expense[] = [
  {
    id: 'exp-1',
    description: 'Electricity bill - April',
    category: 'utilities',
    amount: 450.00,
    date: new Date('2026-04-01'),
    createdBy: 'user-admin-1',
    branchId: 'branch-1',
  },
  {
    id: 'exp-2',
    description: 'Food supplies restock',
    category: 'supplies',
    amount: 1250.00,
    date: new Date('2026-04-05'),
    createdBy: 'user-admin-1',
    branchId: 'branch-1',
  },
  {
    id: 'exp-3',
    description: 'Monthly rent',
    category: 'rent',
    amount: 3000.00,
    date: new Date('2026-04-01'),
    createdBy: 'user-admin-1',
    branchId: 'branch-1',
  },
];
